# Generated by Django 5.1.1 on 2024-10-16 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
        ('facultyapp', '0002_rename_addcourses_addcourse_delete_addcourseform'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AddCourse',
            new_name='AddCourses',
        ),
    ]
