# Generated by Django 5.1.1 on 2024-10-23 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('facultyapp', '0003_rename_addcourse_addcourses'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AddCourses',
        ),
    ]
